const organizationData = {
    "current_page": 1,
    "data": [
        {
            "id": 1,
            "owner_id": 2,
            "org_name": "Công ty Tôn-Từ",
            "phones": "0123-157-6827",
            "description": null,
            "tax_id": "25093",
            "address": "4 Phố Sử, Thôn Khu Liễu, Quận Toản Võ\nBắc Giang",
            "logo_path": "public/docs/logo.png",
            "cover_path": "public/docs/logo.png",
            "is_verify": 1,
            "created_at": "2021-06-12 07:07:30",
            "updated_at": "2021-06-12 07:07:30"
        },
        {
            "id": 2,
            "owner_id": 5,
            "org_name": "Công ty Lô Ltd",
            "phones": "(84)(122)795-9516",
            "description": null,
            "tax_id": "29148",
            "address": "61 Phố Thoa, Phường Kiên Hình, Quận Đàm Liên Phước\nYên Bái",
            "logo_path": "public/docs/logo.png",
            "cover_path": "public/docs/logo.png",
            "is_verify": 1,
            "created_at": "2021-06-12 07:07:30",
            "updated_at": "2021-06-12 07:07:30"
        },
        {
            "id": 3,
            "owner_id": 3,
            "org_name": "Công ty Lý Inc",
            "phones": "(84)(510)525-4168",
            "description": null,
            "tax_id": "70323",
            "address": "588, Thôn Trà, Ấp Lã Chính, Quận Phi Thể Nhân\nBình Dương",
            "logo_path": "public/docs/logo.png",
            "cover_path": "public/docs/logo.png",
            "is_verify": 1,
            "created_at": "2021-06-12 07:07:30",
            "updated_at": "2021-06-12 07:07:30"
        },
        {
            "id": 4,
            "owner_id": 6,
            "org_name": "Công ty Lư, Chung and Liễu",
            "phones": "84-510-295-2105",
            "description": null,
            "tax_id": "86112",
            "address": "314, Ấp Uyên Thân, Ấp Điền Đan, Quận Khương Từ\nSóc Trăng",
            "logo_path": "public/docs/logo.png",
            "cover_path": "public/docs/logo.png",
            "is_verify": 0,
            "created_at": "2021-06-12 07:07:30",
            "updated_at": "2021-06-12 07:07:30"
        },
        {
            "id": 5,
            "owner_id": 3,
            "org_name": "Công ty Đan and Sons",
            "phones": "(84)(199)462-3123",
            "description": null,
            "tax_id": "65777",
            "address": "61 Phố Khâu Cúc Dân, Ấp Cấn Tâm, Huyện Viên Ẩn\nBắc Giang",
            "logo_path": "public/docs/logo.png",
            "cover_path": "public/docs/logo.png",
            "is_verify": 0,
            "created_at": "2021-06-12 07:07:30",
            "updated_at": "2021-06-12 07:07:30"
        },
        {
            "id": 6,
            "owner_id": 8,
            "org_name": "Công ty Lỳ, Hứa and Tòng",
            "phones": "0168-079-4505",
            "description": null,
            "tax_id": "98996",
            "address": "4324 Phố Huỳnh Chiểu Khải, Phường Thụy, Huyện Đường\nHà Nội",
            "logo_path": "public/docs/logo.png",
            "cover_path": "public/docs/logo.png",
            "is_verify": 0,
            "created_at": "2021-06-12 07:07:30",
            "updated_at": "2021-06-12 07:07:30"
        },
        {
            "id": 7,
            "owner_id": 7,
            "org_name": "Công ty Điền and Sons",
            "phones": "(026)346-1265",
            "description": null,
            "tax_id": "65114",
            "address": "1 Phố Diệp Hoan Công, Xã Đoan, Quận 0\nHải Phòng",
            "logo_path": "public/docs/logo.png",
            "cover_path": "public/docs/logo.png",
            "is_verify": 1,
            "created_at": "2021-06-12 07:07:30",
            "updated_at": "2021-06-12 07:07:30"
        },
        {
            "id": 8,
            "owner_id": 7,
            "org_name": "Công ty Khoa, Bành and Phùng",
            "phones": "055-728-7969",
            "description": null,
            "tax_id": "50742",
            "address": "58 Phố Mạch Nhuận Hoán, Thôn Lò Ngôn, Quận Việt Thào\nĐồng Nai",
            "logo_path": "public/docs/logo.png",
            "cover_path": "public/docs/logo.png",
            "is_verify": 0,
            "created_at": "2021-06-12 07:07:30",
            "updated_at": "2021-06-12 07:07:30"
        },
        {
            "id": 9,
            "owner_id": 8,
            "org_name": "Công ty Yên Inc",
            "phones": "(0710)900-0359",
            "description": null,
            "tax_id": "78342",
            "address": "607 Phố Vỹ, Phường Hằng Ngân, Huyện Lan Hiền\nHậu Giang",
            "logo_path": "public/docs/logo.png",
            "cover_path": "public/docs/logo.png",
            "is_verify": 0,
            "created_at": "2021-06-12 07:07:30",
            "updated_at": "2021-06-12 07:07:30"
        },
        {
            "id": 10,
            "owner_id": 3,
            "org_name": "Công ty Ngụy, Nguyễn and Lê",
            "phones": "0126-620-7383",
            "description": null,
            "tax_id": "53649",
            "address": "559, Thôn Thôi Nhuận, Phường 1, Huyện Tuyết Vi\nBình Phước",
            "logo_path": "public/docs/logo.png",
            "cover_path": "public/docs/logo.png",
            "is_verify": 0,
            "created_at": "2021-06-12 07:07:30",
            "updated_at": "2021-06-12 07:07:30"
        }
    ],
    "first_page_url": "https://api.vnjob.work/api/v1/organizations?page=1",
    "from": 1,
    "last_page": 1,
    "last_page_url": "https://api.vnjob.work/api/v1/organizations?page=1",
    "next_page_url": null,
    "path": "https://api.vnjob.work/api/v1/organizations",
    "per_page": 10,
    "prev_page_url": null,
    "to": 10,
    "total": 10
}

export default organizationData;