const recruitmentNewsData = {
    "current_page": 1,
    "data": [
        {
            "id": 1,
            "org_id": 10,
            "author_id": 8,
            "major_id": 3,
            "title": "Fulltime Java",
            "content": "Cần tuyển In eos quos facere corrupti rerum. Qui velit ducimus corporis provident est. Et aut ipsum aut inventore. Cum magnam porro quo ullam exercitationem consequuntur.",
            "address": "4226 Phố Đỗ, Phường 6, Quận Ánh Lai\nHồ Chí Minh",
            "city": "Hồ Chí Minh",
            "work_type": "Part-time",
            "start_time": "2021-06-12 07:07:30",
            "end_time": "2021-06-17 07:07:30",
            "interview_start_time": "2021-06-18 07:07:30",
            "interview_end_time": "2021-06-22 07:07:30",
            "created_at": "2021-06-12 07:07:30",
            "updated_at": "2021-06-12 07:07:30",
            "major": {
                "id": 3,
                "major_name": "BrSE",
                "image_path": "./public/images/major.png",
                "created_at": null,
                "updated_at": null
            }
        },
        {
            "id": 2,
            "org_id": 6,
            "author_id": 1,
            "major_id": 1,
            "title": "Part-time ReactJS",
            "content": "Cần tuyển Voluptate rerum sit quia. Ut ducimus et voluptatem culpa voluptas culpa sit. Ex laborum numquam omnis atque.",
            "address": "8636 Phố Ca, Xã Bì Nguyên Đào, Huyện Lều Huấn Ngọc\nĐắk Lắk",
            "city": "Cần Thơ",
            "work_type": "Remote",
            "start_time": "2021-06-12 07:07:30",
            "end_time": "2021-06-17 07:07:30",
            "interview_start_time": "2021-06-18 07:07:30",
            "interview_end_time": "2021-06-22 07:07:30",
            "created_at": "2021-06-12 07:07:30",
            "updated_at": "2021-06-12 07:07:30",
            "major": {
                "id": 1,
                "major_name": "IT",
                "image_path": "./public/images/major.png",
                "created_at": null,
                "updated_at": null
            }
        },
        {
            "id": 3,
            "org_id": 10,
            "author_id": 4,
            "major_id": 1,
            "title": "Part-time Java",
            "content": "Cần tuyển Fuga qui qui aperiam animi dolores non. Ea quo non et consectetur. Qui repudiandae ea maxime eveniet veniam.",
            "address": "36, Ấp 6, Xã Uyển Vu, Huyện Thôi\nCao Bằng",
            "city": "Hải Phòng",
            "work_type": "Remote",
            "start_time": "2021-06-12 07:07:30",
            "end_time": "2021-06-17 07:07:30",
            "interview_start_time": "2021-06-18 07:07:30",
            "interview_end_time": "2021-06-22 07:07:30",
            "created_at": "2021-06-12 07:07:30",
            "updated_at": "2021-06-12 07:07:30",
            "major": {
                "id": 1,
                "major_name": "IT",
                "image_path": "./public/images/major.png",
                "created_at": null,
                "updated_at": null
            }
        },
        {
            "id": 4,
            "org_id": 6,
            "author_id": 1,
            "major_id": 1,
            "title": "Remote NodeJS",
            "content": "Cần tuyển Eum voluptate ab ipsam nihil. Aliquam laboriosam dignissimos culpa nobis nobis voluptatum. Quis dolor suscipit maxime nostrum. Delectus quod culpa aperiam vitae sit.",
            "address": "85 Phố Thái Hợp Thy, Ấp Danh Thời, Huyện 5\nGia Lai",
            "city": "Hồ Chí Minh",
            "work_type": "Fulltime",
            "start_time": "2021-06-12 07:07:30",
            "end_time": "2021-06-17 07:07:30",
            "interview_start_time": "2021-06-18 07:07:30",
            "interview_end_time": "2021-06-22 07:07:30",
            "created_at": "2021-06-12 07:07:30",
            "updated_at": "2021-06-12 07:07:30",
            "major": {
                "id": 1,
                "major_name": "IT",
                "image_path": "./public/images/major.png",
                "created_at": null,
                "updated_at": null
            }
        },
        {
            "id": 5,
            "org_id": 5,
            "author_id": 7,
            "major_id": 3,
            "title": "Fulltime Ruby",
            "content": "Cần tuyển Sit quidem aut dolorem ut. Et et inventore aut fugit porro. Consequuntur molestiae sapiente perferendis amet minima quas eos. Nihil saepe blanditiis dolorem id dolor necessitatibus atque.",
            "address": "312 Phố Diệp Hậu Diệp, Phường Bạch Nông, Quận Đức Tống\nHà Nội",
            "city": "Cần Thơ",
            "work_type": "Part-time",
            "start_time": "2021-06-12 07:07:30",
            "end_time": "2021-06-17 07:07:30",
            "interview_start_time": "2021-06-18 07:07:30",
            "interview_end_time": "2021-06-22 07:07:30",
            "created_at": "2021-06-12 07:07:30",
            "updated_at": "2021-06-12 07:07:30",
            "major": {
                "id": 3,
                "major_name": "BrSE",
                "image_path": "./public/images/major.png",
                "created_at": null,
                "updated_at": null
            }
        },
        {
            "id": 6,
            "org_id": 8,
            "author_id": 5,
            "major_id": 4,
            "title": "Part-time NodeJS",
            "content": "Cần tuyển Quam nam esse quis repudiandae accusantium doloremque. Molestiae enim odio vero repudiandae nihil. Explicabo temporibus autem a eius. Aut officia consequatur aliquam quia dolore qui.",
            "address": "8787, Thôn Kim Thoại, Phường Quang, Quận 17\nPhú Thọ",
            "city": "Đà Nẵng",
            "work_type": "Part-time",
            "start_time": "2021-06-12 07:07:30",
            "end_time": "2021-06-17 07:07:30",
            "interview_start_time": "2021-06-18 07:07:30",
            "interview_end_time": "2021-06-22 07:07:30",
            "created_at": "2021-06-12 07:07:30",
            "updated_at": "2021-06-12 07:07:30",
            "major": {
                "id": 4,
                "major_name": "Sales",
                "image_path": "./public/images/major.png",
                "created_at": null,
                "updated_at": null
            }
        },
        {
            "id": 7,
            "org_id": 1,
            "author_id": 8,
            "major_id": 4,
            "title": "Fulltime NodeJS",
            "content": "Cần tuyển Molestiae aperiam animi ab. Officia aut perferendis et fugiat ipsum. Deleniti fugiat tempore est voluptatem.",
            "address": "38, Thôn Đường Hà, Phường 14, Quận Chấn Chưởng\nSóc Trăng",
            "city": "Hồ Chí Minh",
            "work_type": "Fulltime",
            "start_time": "2021-06-12 07:07:30",
            "end_time": "2021-06-17 07:07:30",
            "interview_start_time": "2021-06-18 07:07:30",
            "interview_end_time": "2021-06-22 07:07:30",
            "created_at": "2021-06-12 07:07:30",
            "updated_at": "2021-06-12 07:07:30",
            "major": {
                "id": 4,
                "major_name": "Sales",
                "image_path": "./public/images/major.png",
                "created_at": null,
                "updated_at": null
            }
        },
        {
            "id": 8,
            "org_id": 1,
            "author_id": 8,
            "major_id": 3,
            "title": "Part-time .Net",
            "content": "Cần tuyển Maiores vitae possimus eveniet accusamus ad. Tempora fugit architecto fuga illum. Dolores ipsa dicta iste reiciendis impedit perspiciatis illum. Quasi magnam iusto cupiditate sit quaerat.",
            "address": "83 Phố Tú, Ấp Vu Diễm, Huyện 7\nGia Lai",
            "city": "Đà Nẵng",
            "work_type": "Remote",
            "start_time": "2021-06-12 07:07:30",
            "end_time": "2021-06-17 07:07:30",
            "interview_start_time": "2021-06-18 07:07:30",
            "interview_end_time": "2021-06-22 07:07:30",
            "created_at": "2021-06-12 07:07:30",
            "updated_at": "2021-06-12 07:07:30",
            "major": {
                "id": 3,
                "major_name": "BrSE",
                "image_path": "./public/images/major.png",
                "created_at": null,
                "updated_at": null
            }
        },
        {
            "id": 9,
            "org_id": 6,
            "author_id": 6,
            "major_id": 3,
            "title": "Fulltime Ruby",
            "content": "Cần tuyển Et nobis aspernatur optio. Perspiciatis sequi harum doloribus explicabo et vel ducimus. Animi voluptate molestias vel modi. Sit qui nihil aut perspiciatis.",
            "address": "7 Phố Bành, Ấp Hoàn Ly, Quận Khánh\nCần Thơ",
            "city": "Hà Nội",
            "work_type": "Part-time",
            "start_time": "2021-06-12 07:07:30",
            "end_time": "2021-06-17 07:07:30",
            "interview_start_time": "2021-06-18 07:07:30",
            "interview_end_time": "2021-06-22 07:07:30",
            "created_at": "2021-06-12 07:07:30",
            "updated_at": "2021-06-12 07:07:30",
            "major": {
                "id": 3,
                "major_name": "BrSE",
                "image_path": "./public/images/major.png",
                "created_at": null,
                "updated_at": null
            }
        },
        {
            "id": 10,
            "org_id": 1,
            "author_id": 1,
            "major_id": 4,
            "title": "Remote Ruby",
            "content": "Cần tuyển Ratione nemo nisi nemo ea dignissimos quisquam iste enim. Nemo quod ut quos repellendus. Facere et sunt recusandae et.",
            "address": "88, Thôn Bình, Phường Lương, Huyện Thào\nQuảng Ngãi",
            "city": "Hải Phòng",
            "work_type": "Remote",
            "start_time": "2021-06-12 07:07:30",
            "end_time": "2021-06-17 07:07:30",
            "interview_start_time": "2021-06-18 07:07:30",
            "interview_end_time": "2021-06-22 07:07:30",
            "created_at": "2021-06-12 07:07:30",
            "updated_at": "2021-06-12 07:07:30",
            "major": {
                "id": 4,
                "major_name": "Sales",
                "image_path": "./public/images/major.png",
                "created_at": null,
                "updated_at": null
            }
        }
    ],
    "first_page_url": "https://api.vnjob.work/api/v1/recruitment-news?page=1",
    "from": 1,
    "last_page": 5,
    "last_page_url": "https://api.vnjob.work/api/v1/recruitment-news?page=5",
    "next_page_url": "https://api.vnjob.work/api/v1/recruitment-news?page=2",
    "path": "https://api.vnjob.work/api/v1/recruitment-news",
    "per_page": 10,
    "prev_page_url": null,
    "to": 10,
    "total": 45
}

export default recruitmentNewsData;